export const CURRENT_TRANSACTIONS_SUCCESS = "TRANSACTIONS_SUCCESS";
export const CURRENT_TRANSACTIONS_LOADING = "TRANSACTIONS_LOADING";
export const CURRENT_TRANSACTIONS_FAILURE = "TRANSACTIONS_FAILURE";
export const SET_CURRENT_TRANSACTIONS_TABLE_CONFIG = "SET_TRANSACTIONS_TABLE_CONFIG";
export const RESET_CURRENT_TRANSACTIONS = "RESET_TRANSACTIONS";

export const NOT_CURRENT_TRANSACTIONS_SUCCESS = "NOT_CURRENT_TRANSACTIONS_SUCCESS";
export const NOT_CURRENT_TRANSACTIONS_LOADING = "NOT_CURRENT_TRANSACTIONS_LOADING";
export const NOT_CURRENT_TRANSACTIONS_FAILURE = "NOT_CURRENT_TRANSACTIONS_FAILURE";
export const SET_NOT_CURRENT_TRANSACTIONS_TABLE_CONFIG = "SET_NOT_CURRENT_TRANSACTIONS_TABLE_CONFIG";
export const RESET_NOT_CURRENT_TRANSACTIONS = "RESET_NOT_CURRENT_TRANSACTIONS";
