export const CUSTOMERS_SUCCESS = "CUSTOMERS_SUCCESS";
export const CUSTOMERS_FAILURE = "CUSTOMERS_FAILURE";
export const CUSTOMERS_LOADING = "CUSTOMERS_LOADING";
export const CUSTOMERS_PARAMS = "CUSTOMERS_PARAMS";
export const CUSTOMERS_RESET = "CUSTOMERS_RESET";
