export const HOSTING_STATISTICS_SUCCESS = "HOSTING_STATISTICS_SUCCESS";
export const HOSTING_STATISTICS_FAILURE = "HOSTING_STATISTICS_FAILURE";
export const HOSTING_STATISTICS_LOADING = "HOSTING_STATISTICS_LOADING";

