export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";
export const FETCH_USER_INFO_PENDING = "FETCH_USER_INFO_PENDING";
export const FETCH_USER_INFO_ERROR = "FETCH_USER_INFO_ERROR";

export const PATCH_USER_INFO_SUCCESS = "PATCH_USER_INFO_SUCCESS";
export const PATCH_USER_INFO_PENDING = "PATCH_USER_INFO_PENDING";
export const PATCH_USER_INFO_ERROR = "PATCH_USER_INFO_ERROR";

export const SAVE_USER_INFO = "SAVE_USER_INFO";

export const ADD_USER_LANGUAGE = "ADD_USER_LANGUAGE";
export const EDIT_USER_LANGUAGE = "EDIT_USER_LANGUAGE";
export const DELETE_USER_LANGUAGE = "DELETE_USER_LANGUAGE";

export const SET_USER_COMMENTS = "SET_USER_COMMENTS";

// export const UPLOAD_USER_IMAGE = "UPLOAD_USER_IMAGE";
