export const FETCH_CANDIDATES_SUCCESS = "FETCH_CANDIDATES_SUCCESS";
export const FETCH_CANDIDATES_PENDING = "FETCH_CANDIDATES_PENDING";
export const FETCH_CANDIDATES_ERROR = "FETCH_CANDIDATES_ERROR";

export const PATCH_CANDIDATE_SUCCESS = "PATCH_CANDIDATE_SUCCESS";
export const PATCH_CANDIDATE_PENDING = "PATCH_CANDIDATE_PENDING";
export const PATCH_CANDIDATE_ERROR = "PATCH_CANDIDATE_ERROR";


export const ADD_CANDIDATE_SUCCESS = "ADD_CANDIDATE_SUCCESS";
export const ADD_CANDIDATE_PENDING = "ADD_CANDIDATE_PENDING";
export const ADD_CANDIDATE_ERROR = "ADD_CANDIDATE_SUCCESS";


export const DELETE_CANDIDATE_SUCCESS = "DELETE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_PENDING = "DELETE_CANDIDATE_PENDING";
export const DELETE_CANDIDATE_ERROR = "DELETE_CANDIDATE_ERROR";
