export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_PENDING = "FETCH_PROJECTS_PENDING";
export const FETCH_PROJECTS_ERROR = "FETCH_PROJECTS_ERROR";

export const PATCH_PROJECTS_SUCCESS = "PATCH_PROJECTS_SUCCESS";
export const PATCH_PROJECTS_PENDING = "PATCH_PROJECTS_PENDING";
export const PATCH_PROJECTS_ERROR = "PATCH_PROJECTS_ERROR";


export const ADD_PROJECTS_SUCCESS = "ADD_PROJECTS_SUCCESS";
export const ADD_PROJECTS_PENDING = "ADD_PROJECTS_PENDING";
export const ADD_PROJECTS_ERROR = "ADD_PROJECTS_SUCCESS";


export const DELETE_PROJECTS_SUCCESS = "DELETE_PROJECTS_SUCCESS";
export const DELETE_PROJECTS_PENDING = "DELETE_PROJECTS_PENDING";
export const DELETE_PROJECTS_ERROR = "DELETE_PROJECTS_ERROR";
