export const FETCH_CURRENCIES_PENDING = "FETCH_CURRENCIES_PENDING";
export const FETCH_CURRENCIES_SUCCESS = "FETCH_CURRENCIES_SUCCESS";
export const FETCH_CURRENCIES_ERROR = "FETCH_CURRENCIES_ERROR";
