export const HOSTINGS_SUCCESS = "HOSTINGS_SUCCESS";
export const HOSTINGS_FAILURE = "HOSTINGS_FAILURE";
export const HOSTINGS_LOADING = "HOSTINGS_LOADING";
export const HOSTINGS_PARAMS = "HOSTINGS_PARAMS";
export const HOSTINGS_RESET = "HOSTINGS_RESET";
