export const FETCH_CANDIDATE_INFO_SUCCESS = "FETCH_CANDIDATE_INFO_SUCCESS";
export const FETCH_CANDIDATE_INFO_PENDING = "FETCH_CANDIDATE_INFO_PENDING";
export const FETCH_CANDIDATE_INFO_ERROR = "FETCH_CANDIDATE_INFO_ERROR";

export const PATCH_CANDIDATE_INFO_SUCCESS = "PATCH_CANDIDATE_INFO_SUCCESS";
export const PATCH_CANDIDATE_INFO_PENDING = "PATCH_CANDIDATE_INFO_PENDING";
export const PATCH_CANDIDATE_INFO_ERROR = "PATCH_CANDIDATE_INFO_ERROR";

export const SAVE_CANDIDATE_INFO = "SAVE_CANDIDATE_INFO";

export const ADD_CANDIDATE_LANGUAGE = "ADD_CANDIDATE_LANGUAGE";
export const EDIT_CANDIDATE_LANGUAGE = "EDIT_CANDIDATE_LANGUAGE";
export const DELETE_CANDIDATE_LANGUAGE = "DELETE_CANDIDATE_LANGUAGE";

// export const UPLOAD_CANDIDATE_IMAGE = "UPLOAD_CANDIDATE_IMAGE";
