export const VACANCIES_SUCCESS = 'CUSTOMERS_SUCCESS';
export const VACANCIES_FAILURE = 'CUSTOMERS_FAILURE';
export const VACANCIES_LOADING = 'CUSTOMERS_LOADING';
export const VACANCIES_PARAMS = 'CUSTOMERS_PARAMS';
export const VACANCIES_RESET = 'CUSTOMERS_RESET';
