export const FETCH_EMPLOYMENT_TYPES_PENDING = "FETCH_EMPLOYMENT_TYPES_PENDING";
export const FETCH_EMPLOYMENT_TYPES_SUCCESS = "FETCH_EMPLOYMENT_TYPES_SUCCESS";
export const FETCH_EMPLOYMENT_TYPES_ERROR = "FETCH_EMPLOYMENT_TYPES_ERROR";
