import React from 'react';
import Candidates from './CandidatesIcon';
import Customer from './CustomerIcon';
import Dashboard from './DashboardIcon';
import HumanResources from './HumanResourcesIcon';
import Profile from './ProfileIcon';
import Projects from './ProjectsIcon';
import Reports from './ReportsIcon';
import Vacancies from './VacanciesIcon';
import Wallet from './WalletIcon';
import Settings from './SettingsIcon';
import Employees from './EmployeesIcon';
import Caret from './CaretIcon';
import Income from './IncomeIcon';
import Expense from './ExpenseIcon';
import Transfer from './TransferIcon';
import TotalInfo from './TotalInfoIcon';
import Import from './ImportIcon';
import Export from './ExportIcon';
import Filter from './FilterIcon';
import MenuCard from './MenuCardIcon';
import Invoice from './Invoice';
import Calendar from './Calendar';
import InvoiceList from './InvoiceList';

export const CandidatesIcon = () => <Candidates/>;
export const CustomerIcon = () => <Customer/>;
export const DashboardIcon = () => <Dashboard/>;
export const HumanResourcesIcon = () => <HumanResources/>;
export const ProfileIcon = () => <Profile/>;
export const ProjectsIcon = () => <Projects/>;
export const ReportsIcon = () => <Reports/>;
export const VacanciesIcon = () => <Vacancies/>;
export const WalletIcon = () => <Wallet/>;
export const SettingsIcon = () => <Settings/>;
export const EmployeesIcon = () => <Employees/>;
export const CaretIcon = () => <Caret/>;
export const IncomeIcon = () => <Income/>;
export const ExpenseIcon = () => <Expense/>;
export const TransferIcon = () => <Transfer/>;
export const TotalInfoIcon = () => <TotalInfo/>;
export const ImportIcon = () => <Import/>;
export const ExportIcon = () => <Export/>;
export const FilterIcon = () => <Filter/>;
export const MenuCardIcon = () => <MenuCard/>;
export const InvoiceIcon = () => <Invoice/>;
export const CalendarIcon = () => <Calendar/>;
export const InvoiceListIcon = () => <InvoiceList/>;
